### ISSUE TITLE
Install wordpress development environment locally to work on this plugin 

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_wp_search_plugin#3]

**Comment by sopu** [comment]
Since the plugin requires a local installation of wordpress development env. 
I have setup the environment as a sample wordpress website to check the plugin's working.

**Comment by mariobehling** [comment]
@sopu Let's not exaggerate and create issues to set up local wordpress installation. What comes next? "Since the framework required an operating system, I installed Linux on a server"? Please keep it simple and focus on code related issues. We are really looking for more code contributions. Cheers.
